spring:
  application:
    name: bookmyshow

  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow
    username: root
    password: ""  # Or actual password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
